### PR TITLE
[feat] remove stale rows

### LINKED ISSUE #31: Remove Stale Data During Sync
Currently, if we modify the guests or technologies associated with an episode, we'll upsert the data in HCL but not remove anything that was removed from the HCL (because we don't know).

We need to be careful, as we don't want to trigger redundant updates via Hasura by deleting and re-inserting too much data each sync interval.

Perhaps we can DELTE FROM ALL KNOWN TABLES WHERE id NOT IN ["ALL HCL IDS"] ?

### PR DESCRIPTION
**Pull request by icepuma**
Closes #31

### CODE REVIEW

**Comment by icepuma** [comment]
Closes #31.

**Comment by rawkode** [comment]
I’ll need to check how this works with the current `ON DELETE RESTRICT` constraints before approving. I’ll run some tests in the morning.

**Comment by icepuma** [comment]
The sync "should" always work, because we do the sanity check before. I deleted the show `klustered` and the sync stopped with a huge error log complaining, that the show doesn't exist anymore.

**Comment by icepuma** [comment]
Did you test the impact?

**Comment by rawkode** [comment]
Fixed the `down.sql` and confirmed delete works as expected

**Pull request merged**
