### PR TITLE
feat: starting work on the episodes page

### PR DESCRIPTION
**Pull request by allygraham**
@rawkode Is it possible that you can add an `id` property for each episode that I can use as a URL path. I'm currently using the YouTube Id at the moment.

### CODE REVIEW

**Comment by allygraham** [comment]
@rawkode ready to review

**Comment by rawkode** [comment]
Did you merge main?

**Comment by allygraham** [comment]
There was a merge conflict so I rebased. Is that an issue?

**Comment by rawkode** [comment]
Yeah. It’s not rebased correctly. I’ll take a look tonight

**Comment by allygraham** [comment]
Re-created all the changes in another branch

**Pull request closed without merging**
