### PR TITLE
chore(website): bump dependencies

### PR DESCRIPTION
**Pull request by icepuma**
- cal.com integration does not work as of now

### CODE REVIEW

**Comment by icepuma** [comment]
https://github.com/withastro/adapters/pull/436 might be a problem

**Comment by icepuma** [comment]
So, the cal.com react embed component seems to be the only thing that hinders merging this PR. I'll track the releases to make it ready asap

**Comment by rawkode** [comment]
To be honest, I shouldn't be using the embed; I should be using the atoms:

https://cal.com/platform

**Comment by icepuma** [comment]
Sure, feel free!

**Comment by icepuma** [comment]
cal.com integration also works :)

**Review by rawkode — APPROVED** [review]

**Pull request merged**
