### PR TITLE
Feature/new homepage structure

### PR DESCRIPTION
**Pull request by allygraham**

### CODE REVIEW

**Comment by rawkode** [comment]
@allygraham What's the status of this PR? I'm not too sure.

I ran it locally, but I'm assuming it's a WIP?

**Comment by allygraham** [comment]
@rawkode yeah, still WIP. I've updated the title. Need a bit of detail from you:

- **Technologies** I could do with a list. I know there will be data from the API for these but having a list just now allows me to hardcode the data until the API is returning them. I've guessed a few but I'm sure there are more.
- **Shows** More details for them. Do they have their own graphic/illustration? And a short summary for each would be awesome.
- **Trusted By** Looking for a list of your clients you've worked with, not sure if you want to add that to the API at some point as well but if I can get the list then I'll hardcode to start with.
- **Let's work together** I'm planning on using the arms folded pic down there.

**Comment by rawkode** [comment]
Technologies:
- Kubernetes
- Teleport
- Kubescape
- WebAssembly
- Fermyon Spin
- InfluxDB
- Rust
- Loki
- Prometheus
- Grafana
- Thanos
- Dagger (dagger.io)
- Fluentd
- Cilium
- Linkerd
- Open Policy Agent
- Flux
- ArgoCD
- Cortex
- Velero
- Contour Ingress
- Envoy
-

**Comment by rawkode** [comment]
Shows:

No graphics for any

I'll work on descriptions. Lorum ipsum for now, please

**Comment by rawkode** [comment]
Clients:

- Fermyon
- Teleport
- Equinix Metal
- ARMO
- Komodor

**Comment by allygraham** [comment]
@rawkode can you have a look over the homepage and let me know if any copy needs changed?

**Comment by rawkode** [comment]
@allygraham I'm not fussed about the copy, that's easy enough for me to change if required. It all looks fine for now.

**Comment by rawkode** [comment]
@allygraham Done

```graphql
{
  getShows {
    name
    episodes_aggregate {
      aggregate {
        count
      }
    }
  }
}
```

**Comment by rawkode** [comment]
@allygraham 

- [ ] Remove "shows" from menu
- [ ] Make shows on homepage not-clickable (for now)
- [ ] Make "Episode Count" real with new query
- [ ] Merge

**Comment by allygraham** [comment]
@rawkode All changes done apart from merge. Any chance of a thumb?

**Review by rawkode — APPROVED** [review]

**Comment by rawkode** [comment]
@allygraham Deployed

**Pull request merged**
