### PR TITLE
[feat] add "Kubernetes" to the data model 

### PR DESCRIPTION
**Pull request by JOSHUAJEBARAJ**
Added the kubernetes to the data model

### CODE REVIEW

**Comment by rawkode** [comment]
@icepuma First technology PR and I'm thinking we should evolve the tehcnology HCL

```hcl
technology "Kubernetes" {
  draft = false

  description = "Kubernetes, also known as K8s, is an open-source system for automating deployment, scaling, and management of containerized applications"

  website = "https://kubernetes.io/"
  documentation = "https://kubernetes.io/docs/home/"

  open_source {
    repository = "https://github.com/kubernetes/kubernetes"
  }
}
```

- [ ] I think we can make the open_source and repository a block
  - If no block, open_source = false
  - If a block, open_source = true and repository is mandatory
- [ ] Description may become over loaded here, so I'm thinking
  - Description should be used for SEO. It should be 300-500 characters (AutoGenerated from GPT and/or Wikipedia?)
  - Add a "Tagline" which for Kubernetes would be the current description: "Kubernetesis an open-source system for automating deployment, scaling, and management of containerized applications"
- [ ] Add HashTags/Tags list
- [ ] Add Aliases list (K8s)

Anything else that would be useful?

Feedback from you @JOSHUAJEBARAJ would be great also

**Comment by rawkode** [comment]
ChatGPT generated this from my Kubernetes example :)

```hcl
technology "prometheus" {
  draft = false

  name = "Prometheus"
  aliases = [
    "Prometheus Monitoring"
  ]

  tagline = "An open-source monitoring and alerting platform for cloud native environments"
  description = <<-END
    Prometheus is an open-source monitoring and alerting platform designed for cloud native environments. It features a multi-dimensional data model, a flexible query language, and a variety of powerful visualization and alerting tools.
    
    Prometheus is designed to be easy to deploy and operate, and can be integrated with a variety of other tools and platforms. It is highly scalable and can handle large amounts of data and a high volume of requests.
    
    Some key features of Prometheus include a powerful query language, support for metric recording and alerting, support for distributed architectures, and integrations with a variety of tools and platforms.
  END

  website = "https://prometheus.io/"
  documentation = "https://prometheus.io/docs/"

  tags = [
    "Monitoring",
    "Alerting",
    "Cloud Native",
    "Data Modeling",
    "Visualization",
    "Scalability"
  ]

  open_source {
    repository = "https://github.com/prometheus/prometheus"
  }
}
```

**Comment by icepuma** [comment]
Will think about it after the hackathon call

**Comment by rawkode** [comment]
@JOSHUAJEBARAJ Can you update to the new format? The changes to support the extra fields has been merged.

**Comment by JOSHUAJEBARAJ** [comment]
Hey @rawkode  Sure will do Just want to make sure we are using this format right ? 
https://raw.githubusercontent.com/RawkodeAcademy/RawkodeAcademy/main/projects/rawkode.studio/content-management/data/technologies/rust.hcl

**Comment by rawkode** [comment]
Yes. All the fields in the examples above are valid

**Comment by JOSHUAJEBARAJ** [comment]
Closing this PR and creating a new PR

**Pull request closed without merging**
