### PR TITLE
feat: modify target for external links

### PR DESCRIPTION
**Pull request by martintc**
issue #116

### CODE REVIEW

**Comment by rawkode** [comment]
While this approach will certainly work, it relies on modifying the page client side. 

We use the Astro content collections for the blog and specifically `renderContent` method.

I believe we can pass in our own Link component, which could contain this logic and allows us to ship pretendered HTML

**Comment by icepuma** [comment]
Maybe https://docs.astro.build/en/recipes/external-links/ also works

**Comment by rawkode** [comment]
Good find, @icepuma. Docs are here:

https://github.com/rehypejs/rehype-external-links?tab=readme-ov-file#use

**Review by rawkode — APPROVED** [review]

**Comment by rawkode** [comment]
@martintc Merged manually, as I had to rebase.

**Pull request closed without merging**
