### PR TITLE
feat(website): add article cover to the opengraph image

### PR DESCRIPTION
**Pull request by icepuma**
We have to test this one, as I'm using https://docs.astro.build/en/reference/modules/astro-assets/#getimage here

### CODE REVIEW

**Comment by icepuma** [comment]
It seems to work in general, but I have to fix one thing :)

https://www.opengraph.xyz/url/https%3A%2F%2F8a7f1565.rawkode-academy.pages.dev%2Fblog%2Fzed-show-and-tell%2F

**Comment by rawkode** [comment]
Looks good!

**Comment by icepuma** [comment]
* https://www.opengraph.xyz/url/https%3A%2F%2F8dd0b6ab.rawkode-academy.pages.dev%2Fseries%2Ftalos-on-hetzner%2F
* https://www.opengraph.xyz/url/https%3A%2F%2F8dd0b6ab.rawkode-academy.pages.dev%2Fblog%2Four-architecture%2F

**Review by rawkode — APPROVED** [review]

**Comment by rawkode** [comment]
Merge if you're happy

**Pull request merged**
